SELECT * FROM PRODUCT;
SELECT * FROM STOCK;
SELECT * FROM PRODORDER;
SELECT * FROM STORE;
-- 본사 재고 조회
SELECT p.PRODUCTNUM ,p.CATEGORY ,p.PRODUCTNAME ,p.OPPOSITE ,p.PRICE ,p2.AMOUNT ,p2.ORDERSTATE ,p.REMARK 
FROM PRODUCT p , PRODORDER p2 
WHERE p.PRODUCTNUM = p2.PRODUCTNUM 
AND p.productNum LIKE '%'||''||'%'
AND category LIKE '%'||''||'%'
AND productName LIKE '%'||''||'%'
AND opposite LIKE '%'||''||'%'
AND orderState LIKE '%'||''||'%';
SELECT DISTINCT orderState FROM PRODORDER;
-- 본사 재고 등록
INSERT INTO PRODUCT VALUES ('PD'||pdSeq.nextval, #{category}, 
#{productName}, #{opposite}, #{price}, #{img}, #{remark});
-- 본사 재고 수정
UPDATE PRODUCT
SET productNum = #{productNum},
	category = #{category},
	productName = #{productName},
	opposite = #{opposite},
	price = #{price},
	img = #{img},
	remark = #{remark}
WHERE productNum = #{productNum};
-- 본사 매매내역 조회
-- 매장 재고 조회
SELECT s.STOCKDATE ,p.PRODUCTNUM ,p.CATEGORY ,p.OPPOSITE ,p.PRICE ,p2.AMOUNT ,p2.ORDERSTATE ,p.REMARK 
FROM PRODUCT p , STOCK s , PRODORDER p2 
WHERE p.PRODUCTNUM = s.PRODUCTNUM 
AND p.PRODUCTNUM = p2.PRODUCTNUM 
AND stockDate LIKE '%'||''||'%'
AND p.productNum LIKE '%'||''||'%'
AND category LIKE '%'||''||'%'
AND productName LIKE '%'||''||'%'
AND opposite LIKE '%'||''||'%'
AND orderState LIKE '%'||''||'%';
-- 매장 매매내역 조회
SELECT s.STOCKDATE ,p.ORDERNUM ,p2.PRODUCTNUM ,p2.CATEGORY ,p2.PRODUCTNAME ,p2.OPPOSITE ,p2.PRICE ,s.APPLYAMOUNT ,p.PAYMENTSTATE ,s.REMARK 
FROM STOCK s ,PRODORDER p ,PRODUCT p2
WHERE p2.PRODUCTNUM = s.PRODUCTNUM 
AND p2.PRODUCTNUM = p.PRODUCTNUM ;
-- 매장 매매내역 등록
-- 매장 매매내역 수정
-- 매장 매매내역 삭제

SELECT TO_CHAR(s.stockDate,'YYYY-MM-DD') stockDate ,p.PRODUCTNUM ,p.CATEGORY ,p.PRODUCTNAME ,p.OPPOSITE ,p.PRICE ,p2.AMOUNT ,p2.ORDERSTATE ,p.REMARK 
		FROM PRODUCT p , STOCK s , PRODORDER p2 
		WHERE p.PRODUCTNUM = s.PRODUCTNUM 
		AND p.PRODUCTNUM = p2.PRODUCTNUM 
		AND stockDate = to_date('2023-02-11','YYYY-MM-DD');
SELECT TO_CHAR(s.stockDate,'YYYY-MM-DD') stockDate
		,p.PRODUCTNUM ,p.CATEGORY ,p.PRODUCTNAME ,p.OPPOSITE ,p.PRICE
		,p2.AMOUNT ,p2.ORDERSTATE ,p.REMARK
		FROM PRODUCT p , STOCK s , PRODORDER p2
		WHERE p.PRODUCTNUM = s.PRODUCTNUM
		AND p.PRODUCTNUM = p2.PRODUCTNUM
		AND s.stockDate LIKE '%'|| to_date('2023-02-28','YYYY-MM-DD')||'%';
	
----------------------------------
SELECT * FROM PRODORDER p ;
SELECT * FROM STOCK s ;
SELECT * FROM PRODUCT p ;	
-- 본사/매장 재고 조회(자재코드별로 최근일자의 자재수량 조회)
SELECT p.*, s.stockDate, s.REMAINAMOUNT, s.FRREGINUM 
FROM PRODUCT p, STOCK s
WHERE p.PRODUCTNUM = s.PRODUCTNUM
AND s.STOCKDATE = (
  SELECT MAX(STOCKDATE) FROM STOCK s2
  WHERE s2.PRODUCTNUM = p.PRODUCTNUM)
AND stockDate LIKE '%'|| to_date('','YYYY-MM-DD')||'%'
AND p.productNum LIKE '%'||''||'%'
AND category LIKE '%'||''||'%'
AND productName LIKE '%'||''||'%'
AND opposite LIKE '%'||''||'%'
AND s.frRegiNum = '9999999999';
-- 매장 재고 매매내역조회
SELECT DISTINCT p.PRODUCTNUM, p.PRODUCTNAME, p.CATEGORY, p2.ORDERNUM, p2.ORDERDATE, p2.AMOUNT, p2.PAYMENTSTATE, p2.ORDERSTATE
FROM PRODUCT p
INNER JOIN PRODORDER p2 ON p.PRODUCTNUM = p2.PRODUCTNUM
INNER JOIN STOCK s ON p.PRODUCTNUM = s.PRODUCTNUM;
-- 매장 재고 매출내역등록
INSERT INTO STOCK 
VALUES ('PD10002', '9999999999', sysdate, 3, 
        (SELECT REMAINAMOUNT + 3 
         FROM STOCK 
         WHERE PRODUCTNUM = 'PD10002' AND STOCKDATE = (SELECT MAX(STOCKDATE) FROM STOCK WHERE PRODUCTNUM = 'PD10002')), 
        null);
-- 매장 재고 매출내역수정
UPDATE STOCK 
SET APPLYAMOUNT = 4,
    REMAINAMOUNT = (
        SELECT REMAINAMOUNT + 4 - APPLYAMOUNT 
        FROM (
            SELECT REMAINAMOUNT, ROW_NUMBER() OVER (ORDER BY STOCKDATE DESC) AS RN 
            FROM STOCK 
            WHERE PRODUCTNUM = 'PD10002'
        ) T 
        WHERE RN = 1
    )
WHERE PRODUCTNUM = 'PD10002' AND STOCKDATE = (SELECT MAX(STOCKDATE) FROM STOCK WHERE PRODUCTNUM = 'PD10002');
-- 매장 재고 매출내역삭제
DELETE FROM STOCK 
WHERE PRODUCTNUM = 'PD10002' 
AND APPLYAMOUNT = 4
AND REMAINAMOUNT = 44;
-- 본사 재고 등록
INSERT INTO PRODUCT VALUES ('PD'||pdSeq.nextval, '', '', '', '', '', '');
-- 본사 재고 수정
UPDATE PRODUCT 
SET REMARK  = ''
WHERE PRODUCTNUM = 'PD10001';
-- 본사 재고 매매내역조회
SELECT DISTINCT p.PRODUCTNUM, p.PRODUCTNAME, p.CATEGORY, p2.ORDERNUM, p2.ORDERDATE, p2.AMOUNT, p2.PAYMENTSTATE, p2.ORDERSTATE
FROM PRODUCT p
INNER JOIN PRODORDER p2 ON p.PRODUCTNUM = p2.PRODUCTNUM
INNER JOIN STOCK s ON p.PRODUCTNUM = s.PRODUCTNUM
WHERE s.FrRegiNum = '9999999999';
