SELECT * FROM account ;

INSERT INTO ACCOUNT values('10100','자산','현금');
ALTER TABLE statement RENAME TO ACStatement;
ALTER TABLE ACSTATEMENT RENAME COLUMN debt TO debit;

UPDATE account SET ACNTUSING = 0 WHERE acntnum='10110';

INSERT INTO acstatement values('A0001','10174252589','11100',1000,0,null,sysdate,null);
INSERT INTO acstatement values('A0001','10174252589','11200',0,1000,null,sysdate,null);
   SELECT count(DISTINCT statementNum) FROM ACSTATEMENT a WHERE TO_CHAR(stmtdate,'YYYY-MM-DD') = '2023-02-23';

--첫번째거는 +1, 뒤에거는 그냥
INSERT INTO ACSTATEMENT values('A'||to_char((SELECT count(DISTINCT statementNum)+1 FROM ACSTATEMENT a WHERE TO_CHAR(stmtdate,'YYYY-MM-DD') = '2023-02-23'),'FM0000'),'1000','11200',0,1000,null,sysdate,null);
INSERT INTO ACSTATEMENT values('A'||to_char((SELECT count(DISTINCT statementNum) FROM ACSTATEMENT a WHERE TO_CHAR(stmtdate,'YYYY-MM-DD') = '2023-02-23'),'FM0000'),'1000','77300',1000,0,null,sysdate,null);

INSERT INTO ACSTATEMENT 
	values('A'||to_char((SELECT count(DISTINCT statementNum)+1 FROM ACSTATEMENT a WHERE TO_CHAR(stmtdate,'YYYY-MM-DD') = '2023-02-23'),'FM0000'),
		'1000','11100',0,10000,null,sysdate,null);
INSERT INTO ACSTATEMENT 
	values('A'||to_char((SELECT count(DISTINCT statementNum) FROM ACSTATEMENT a WHERE TO_CHAR(stmtdate,'YYYY-MM-DD') = '2023-02-23'),'FM0000'),
		'1000','77300',10000,0,null,sysdate,null);


SELECT * FROM ACSTATEMENT a ;
SELECT max(STATEMENTNUM) FROM ACSTATEMENT a;

UPDATE ACSTATEMENT SET acntnum= 10100, debit=3000, credit=0,STMTOPPOSITE ='정기거래처',REMARK ='참고용' WHERE STATEMENTNUM ='A0001' AND TO_CHAR(stmtdate,'YYYY-MM-DD') = '2023-02-01' AND lineNum=0;

SELECT * FROM ACSTATEMENT a WHERE TO_CHAR(stmtdate,'YYYY-MM-DD') ='2023-02-23' AND STATEMENTNUM = (SELECT min(STATEMENTNUM) FROM ACSTATEMENT a2);

--DELETE FROM ACSTATEMENT a ;

SELECT TO_DATE('2022-11-11','YYYY-MM-DD') FROM dual; 

SELECT * FROM Account where acntNum Like '%'||''||'%' And acntTitle LIKE '%'||'현'||'%';
DROP TABLE ACSTATEMENT ;

--전표목록 조회
SELECT a.ACNTGROUP, s.* FROM ACSTATEMENT s, ACCOUNT a 
WHERE s.acntnum = a.acntnum 
AND a.ACNTNUM = 10100
AND (STMTOPPOSITE IS NULL OR STMTOPPOSITE LIKE '%'||''||'%')
AND STMTDATE BETWEEN TO_DATE('2023-02-01','YYYY-MM-DD') AND TO_DATE('2023-02-10','YYYY-MM-DD')
;

SELECT STATEMENTNUM,
	CASE WHEN acntgroup='비용' THEN debit-credit 
	WHEN acntgroup='자산' THEN debit-credit
	ELSE CREDIT - debit END AS DEBIT,
	STMTOPPOSITE,TO_CHAR(STMTDATE,'YYYY-MM-DD') "STMTDATE", REMARK FROM ACSTATEMENT s , ACCOUNT a
WHERE s.ACNTNUM = a.ACNTNUM 
AND s.ACNTNUM = 40100
AND (STMTOPPOSITE IS NULL OR STMTOPPOSITE LIKE '%'||''||'%')
AND STMTDATE BETWEEN TO_DATE('2023-02-01','YYYY-MM-DD') AND TO_DATE('2023-02-10','YYYY-MM-DD')
AND FRREGINUM = 'fakeID1111'
;

SELECT acntgroup,
CASE WHEN acntgroup='비용' THEN debit-credit 
	WHEN acntgroup='자산' THEN debit-credit
	ELSE CREDIT - debit END AS DEBIT 
FROM ACSTATEMENT s , ACCOUNT a
WHERE s.ACNTNUM = a.ACNTNUM 
AND s.acntnum='40100';

SELECT TO_CHAR(STMTDATE,'YYYY-MM-DD') AS "STMTDATE" ,
		sum(CASE WHEN acntgroup='비용' THEN debit-credit 
		WHEN acntgroup='자산' THEN debit-credit
		ELSE CREDIT - debit END) AS DEBIT
	FROM ACSTATEMENT s , ACCOUNT a
WHERE s.ACNTNUM = a.ACNTNUM 
AND s.ACNTNUM = 40100
AND (STMTOPPOSITE IS NULL OR STMTOPPOSITE LIKE '%'||''||'%')
AND STMTDATE BETWEEN TO_DATE('2023-02-01','YYYY-MM-DD') AND TO_DATE('2023-02-10','YYYY-MM-DD')
AND FRREGINUM = 'fakeID1111'
	GROUP BY STMTDATE;